abstract class QuranStates{}
class QuranInitStates extends QuranStates{}
class QuranLoadJsonLoadingStates extends QuranStates{}
class QuranLoadJsonSuccessStates extends QuranStates{}
class QuranGetAzkarLoadingStates extends QuranStates{}
class QuranGetAzkarSuccessStates extends QuranStates{}
class QuranGetAzkarErrorStates extends QuranStates{}
class QuranLoadJsonrecitersSuccessStates extends QuranStates{}
class QuranLoadJsonErrorStates extends QuranStates{}
class QuranGetStartedStates extends QuranStates{}
class QuranbuttonTextsTapStates extends QuranStates{}
class QuranChangeGuzStates extends QuranStates{}
class QuranazkartapChangeStates extends QuranStates{}
class QuranRemoveAzkarStates extends QuranStates{}
class QuranHasLocationPermissionStates extends QuranStates{}
class QuranCalculatePrayerTimesStates extends QuranStates{}
class QuranChangePlayAudioIconStates extends QuranStates{}
class QuranChangePlayAudioIconStates2 extends QuranStates{}
class QuranGetCashStates extends QuranStates{}
class QuranEnableWakelockStates extends QuranStates{}
class QuranDisableWakelockStates extends QuranStates{}
class QuranDarkModeStates extends QuranStates{}
class QuranchangeLangStates extends QuranStates{}
class QuranchangeDrawerLangStates extends QuranStates{}
class QuranchangeDrawerModeStates extends QuranStates{}
class QuranchangeDrawerFontSizeStates extends QuranStates{}
class QuranchangeDrawerScreenTimeStates extends QuranStates{}
class QuranchangeDrawerShowClockStates extends QuranStates{}
class QuranGetSearchStates extends QuranStates{}
class QuranGetSurahSearchStates extends QuranStates{}
class QuranGetFourSuccessStates extends QuranStates{}
class QuranGetFourErrorStates extends QuranStates{}
class QuranShowSearchSuccessStates extends QuranStates{}
class QuranSGuizNumStates extends QuranStates{}
